### ISSUE TITLE
Quebra de imagem salvar alterações do Ambiente 

### ISSUE THREAD

**Issue by leandromarquesrr** [Openredu/Openredu#134]
Descrição: Quebra de imagem do Ambiente ao salvar alterações

Etapas: Estar logado>Ambientes>Abrir um ambiente que o usuário está inserido>Clicar em "Gerenciar ambiente">Inserir em "Abreviação" texto longo, ex: 28 caracteres>Inserir caracteres em"Endereço">Clicar em "Escolher arquivo">Selecionar um arquivo de imagem>Clicar em "Salvar alterações">.
Resultado: Imagem do ambiente quebra e não é exibida.
Resultado esperado: Salvar e exibir a imagem solicitada.
![issue - quebra de imagem do curso](https://cloud.githubusercontent.com/assets/24481765/26209780/1f66b4fa-3bc4-11e7-99ce-07cb416be8bf.PNG)

Versão: N/A
OS: Windows 10

**Comment by Bouckaert** [comment]
Log durante a reprodução do bug:

``` ruby
Started PUT "/ambiente-de-comunicacaojjjjjjjjjjjjjjjgnfgmndfnd" for 150.161.41.13 at 2017-05-18 13:49:06 -0400
Processing by EnvironmentsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"SGS8ckS347PEYy/H7GFBdJJvdF0GYhAZiUZz75yJUNI=", "environment"=>{"name"=>"Ambiente de Comunicação", "initials"=>"ambcomgbdlo~gaoagogpga~dpãgdf", "path"=>"ambiente-de-comunicacaojjjjjjjjjjjjjjjgnfgmndfnd", "description"=>"", "tag_list"=>"openredu", "avatar"=>#<ActionDispatch::Http::UploadedFile:0x0000000c33c438 @original_filename="02.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"environment[avatar]\"; filename=\"02.jpg\"\r\nContent-Type: image/jpeg\r\n", @tempfile=#<File:/tmp/RackMultipart20170518-11479-1r9w1fs>>}, "commit"=>"Salvar alterações", "locale"=>"pt-BR", "id"=>"ambiente-de-comunicacaojjjjjjjjjjjjjjjgnfgmndfnd"}
  Environment Load (0.2ms)  SELECT `environments`.* FROM `environments` WHERE `environments`.`path` = 'ambiente-de-comunicacaojjjjjjjjjjjjjjjgnfgmndfnd' LIMIT 1
  User Load (0.2ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 8216 LIMIT 1
  UserEnvironmentAssociation Load (0.2ms)  SELECT `user_environment_associations`.* FROM `user_environment_associations` WHERE `user_environment_associations`.`user_id` = 8216 AND `user_environment_associations`.`environment_id` = 2422 LIMIT 1
   (0.2ms)  BEGIN
  ActsAsTaggableOn::Tag Load (0.4ms)  SELECT `tags`.* FROM `tags` INNER JOIN `taggings` ON `tags`.`id` = `taggings`.`tag_id` WHERE `taggings`.`taggable_id` = 2422 AND `taggings`.`taggable_type` = 'Environment' AND (taggings.context = 'tags' AND taggings.tagger_id IS NULL)
Command :: identify -format %wx%h '/tmp/stream20170518-11479-wn2xiy.jpg[0]'
Command :: convert '/tmp/stream20170518-11479-wn2xiy.jpg[0]' -resize "x32" -crop "32x32+9+0" +repage '/tmp/stream20170518-11479-wn2xiy20170518-11479-1x4nkps'
Command :: identify -format %wx%h '/tmp/stream20170518-11479-wn2xiy.jpg[0]'
Command :: convert '/tmp/stream20170518-11479-wn2xiy.jpg[0]' -resize "x90" -crop "90x90+26+0" +repage '/tmp/stream20170518-11479-wn2xiy20170518-11479-xg1mzr'
Command :: identify -format %wx%h '/tmp/stream20170518-11479-wn2xiy.jpg[0]'
Command :: convert '/tmp/stream20170518-11479-wn2xiy.jpg[0]' -resize "x140" -crop "140x140+41+0" +repage '/tmp/stream20170518-11479-wn2xiy20170518-11479-1t6mvvd'
  Environment Exists (1.1ms)  SELECT 1 AS one FROM `environments` WHERE (`environments`.`name` = BINARY 'Ambiente de Comunicação' AND `environments`.`id` != 2422) LIMIT 1
  Environment Exists (0.6ms)  SELECT 1 AS one FROM `environments` WHERE (`environments`.`path` = BINARY 'ambiente-de-comunicacaojjjjjjjjjjjjjjjgnfgmndfnd' AND `environments`.`id` != 2422) LIMIT 1
   (0.2ms)  ROLLBACK
  Rendered shared/_management_background.html.erb (0.1ms)
Read fragment views/environment_sidebar_connections_with_count/2422 (0.5ms)
  Rendered environments/_sidebar.html.erb (5.0ms)
  Rendered environments/_breadcrumbs.html.erb (1.5ms)
  Rendered environments/admin/_header.html.erb (1.3ms)
  Rendered environments/admin/_clean_header.html.erb (0.1ms)
  Plan Load (0.2ms)  SELECT `plans`.* FROM `plans` WHERE `plans`.`billable_id` = 2422 AND `plans`.`billable_type` = 'Environment' AND `plans`.`current` = 1 LIMIT 1
  Rendered shared/_tabs.html.erb (0.1ms)
  Rendered environments/admin/edit.html.erb within layouts/application (30.8ms)
  Rendered shared/_typekit.html.erb (0.6ms)
  Rendered shared/_analytics.html.erb (0.1ms)
  Rendered shared/_outdated_browser.html.erb (0.2ms)
  Rendered shared/_loading_message.html.erb (0.1ms)
  Rendered shared/_form_search.html.erb (0.9ms)
Read fragment views/nav_global_dropdown_menu/8216 (0.3ms)
  Rendered shared/_nav_global.html.erb (13.3ms)
  Rendered shared/_header.html.erb (14.1ms)
  Rendered shared/_flash_message.html.erb (0.1ms)
  Rendered shared/_footer_old.html.erb (2.2ms)
Completed 200 OK in 723ms (Views: 54.8ms | ActiveRecord: 3.3ms | Solr: 0.0ms)
Started GET "/images/environments/avatars/2422/thumb_140/02.jpg?1495129746" for 150.161.41.13 at 2017-05-18 13:49:07 -0400

ActionController::RoutingError (No route matches [GET] "/images/environments/avatars/2422/thumb_140/02.jpg"):
  actionpack (3.2.13) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.13) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.13) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.13) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.13) lib/rails/engine.rb:479:in `call'
  railties (3.2.13) lib/rails/application.rb:223:in `call'
  railties (3.2.13) lib/rails/railtie/configurable.rb:30:in `method_missing'
  unicorn (5.1.0) lib/unicorn/http_server.rb:562:in `process_client'
  unicorn (5.1.0) lib/unicorn/http_server.rb:658:in `worker_loop'
  unicorn (5.1.0) lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
  unicorn (5.1.0) lib/unicorn/http_server.rb:132:in `start'
  unicorn (5.1.0) bin/unicorn_rails:209:in `<top (required)>'
  /mnt/openredu-staging/shared/bundle/ruby/1.9.1/bin/unicorn_rails:23:in `load'
  /mnt/openredu-staging/shared/bundle/ruby/1.9.1/bin/unicorn_rails:23:in `<top (required)>'
  bundler (1.14.6) lib/bundler/cli/exec.rb:74:in `load'
  bundler (1.14.6) lib/bundler/cli/exec.rb:74:in `kernel_load'
  bundler (1.14.6) lib/bundler/cli/exec.rb:27:in `run'
  bundler (1.14.6) lib/bundler/cli.rb:335:in `exec'
  bundler (1.14.6) lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  bundler (1.14.6) lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  bundler (1.14.6) lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  bundler (1.14.6) lib/bundler/cli.rb:20:in `dispatch'
  bundler (1.14.6) lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  bundler (1.14.6) lib/bundler/cli.rb:11:in `start'
  bundler (1.14.6) exe/bundle:32:in `block in <top (required)>'
  bundler (1.14.6) lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  bundler (1.14.6) exe/bundle:24:in `<top (required)>'
  /usr/local/rubies/1.9.3-p551/bin/bundle:23:in `load'
  /usr/local/rubies/1.9.3-p551/bin/bundle:23:in `<main>'


Processing by EnvironmentsController#show as HTML
  Parameters: {"1495129746"=>nil, "locale"=>"pt-BR", "id"=>"404"}
  Environment Load (1.1ms)  SELECT `environments`.* FROM `environments` WHERE `environments`.`path` = '404' LIMIT 1
Couldn't find Environment with path = 404
  Rendered errors/404.html.erb within layouts/cold (3.1ms)
  Rendered shared/_typekit.html.erb (0.5ms)
  Rendered shared/_flash_message.html.erb (0.1ms)
Completed 404 Not Found in 30ms (Views: 11.2ms | ActiveRecord: 1.1ms | Solr: 0.0ms)
```

**Comment by Bouckaert** [comment]
Relacionada com #133
