### ISSUE TITLE
Erro ao tentar carregar esquema do banco

### ISSUE THREAD

**Issue by paulolieuthier** [OpenRedu/OpenRedu#14]
```shell
$ bundle exec rake db:create
$ bundle exec rake db:schema:load        
rake aborted!
Mysql2::Error: Table 'redu_development.course_enrollments' doesn't exist: SHOW FULL FIELDS FROM `course_enrollments`
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `execute'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/connection_adapters/mysql2_adapter.rb:211:in `execute'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:259:in `execute_and_free'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:426:in `columns'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/connection_adapters/schema_cache.rb:12:in `block in initialize'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/model_schema.rb:228:in `yield'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/model_schema.rb:228:in `default'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/model_schema.rb:228:in `columns'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/model_schema.rb:237:in `columns_hash'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/inheritance.rb:19:in `descends_from_active_record?'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/inheritance.rb:25:in `finder_needs_type_condition?'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/base.rb:455:in `relation'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/scoping/named.rb:37:in `scoped'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/querying.rb:9:in `where'
/home/paulo/Desktop/redu/app/models/user_course_association.rb:26:in `<class:UserCourseAssociation>'
/home/paulo/Desktop/redu/app/models/user_course_association.rb:2:in `<top (required)>'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:469:in `load'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:469:in `block in load_file'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:639:in `new_constants_in'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:468:in `load_file'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:353:in `require_or_load'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:502:in `load_missing_constant'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:192:in `block in const_missing'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:190:in `each'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:190:in `const_missing'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/inflector/methods.rb:230:in `block in constantize'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/inflector/methods.rb:229:in `each'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/inflector/methods.rb:229:in `constantize'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/core_ext/string/inflections.rb:54:in `constantize'
/home/paulo/Desktop/redu/app/doorkeepers/base_doorkeeper.rb:8:in `block in initialize'
/home/paulo/Desktop/redu/app/doorkeepers/base_doorkeeper.rb:6:in `each'
/home/paulo/Desktop/redu/app/doorkeepers/base_doorkeeper.rb:6:in `initialize'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/untied-publisher-0.0.7.pre3/lib/untied-publisher/railtie.rb:16:in `new'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/untied-publisher-0.0.7.pre3/lib/untied-publisher/railtie.rb:16:in `block in <class:Railtie>'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:429:in `_run__2149553168065986602__prepare__2544178207439652814__callbacks'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/actionpack-3.2.13/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/actionpack-3.2.13/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `instance_exec'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `run'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `each'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `run_initializers'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/application.rb:136:in `initialize!'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/paulo/Desktop/redu/config/environment.rb:6:in `<top (required)>'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/application.rb:103:in `require_environment!'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/application.rb:297:in `block (2 levels) in initialize_tasks'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:205:in `block in invoke_prerequisites'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:183:in `block in invoke_with_call_chain'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:schema:load => environment
(See full trace by running task with --trace)
```

**Comment by paulolieuthier** [comment]
```
$ mysql -u localhost -u root -p -e "use redu_development; show tables"
$
```

**Comment by paulolieuthier** [comment]
Valeu! Mas ainda tem outro erro. Tanto o `db:schema:load` quanto o `db:migrate` geram a mesma saída:
```shell
$ rake db:schema:load --trace
** Invoke db:schema:load (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
undefined method `aasm_initial_state' for UserCourseAssociation(Table doesn't exist):Class
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-3.2.13/lib/active_record/dynamic_matchers.rb:55:in `method_missing'
/home/paulo/Desktop/redu/app/models/user_course_association.rb:38:in `<class:UserCourseAssociation>'
/home/paulo/Desktop/redu/app/models/user_course_association.rb:2:in `<top (required)>'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:469:in `load'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:469:in `block in load_file'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:639:in `new_constants_in'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:468:in `load_file'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:353:in `require_or_load'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:502:in `load_missing_constant'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:192:in `block in const_missing'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:190:in `each'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:190:in `const_missing'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/inflector/methods.rb:230:in `block in constantize'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/inflector/methods.rb:229:in `each'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/inflector/methods.rb:229:in `constantize'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/core_ext/string/inflections.rb:54:in `constantize'
/home/paulo/Desktop/redu/app/doorkeepers/base_doorkeeper.rb:8:in `block in initialize'
/home/paulo/Desktop/redu/app/doorkeepers/base_doorkeeper.rb:6:in `each'
/home/paulo/Desktop/redu/app/doorkeepers/base_doorkeeper.rb:6:in `initialize'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/untied-publisher-0.0.7.pre3/lib/untied-publisher/railtie.rb:16:in `new'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/untied-publisher-0.0.7.pre3/lib/untied-publisher/railtie.rb:16:in `block in <class:Railtie>'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:429:in `_run__3994830042155718719__prepare__482374971968461807__callbacks'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/actionpack-3.2.13/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/actionpack-3.2.13/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `instance_exec'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `run'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `each'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `run_initializers'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/application.rb:136:in `initialize!'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/paulo/Desktop/redu/config/environment.rb:6:in `<top (required)>'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/application.rb:103:in `require_environment!'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/application.rb:297:in `block (2 levels) in initialize_tasks'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/home/paulo/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:205:in `block in invoke_prerequisites'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:183:in `block in invoke_with_call_chain'
/home/paulo/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/bin/rake:33:in `<top (required)>'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/bin/rake:23:in `load'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/bin/rake:23:in `<main>'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/paulo/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:schema:load => environment
```

**Comment by paulolieuthier** [comment]
@Bouckaert você poderia reabrir a issue?

**Comment by Bouckaert** [comment]
@paulolieuthier  Reabri a issue pq de fato precisamos consertar o db:schema:load. Mas não entendo o db:migrate falhar!
O rake db:create rodou? O banco foi criado? Confirmasse se as credenciais do database.yml estão corretas? Posta aqui a saída do rake db:migrate pfv!

**Comment by paulolieuthier** [comment]
Consegui! Refiz tudo do zero e executei assim:
```
$ bundle exec rake db:create
$ bundle exec rake db:migrate
```

**Comment by embs** [comment]
> Reabri a issue pq de fato precisamos consertar o db:schema:load

@Bouckaert, o `schema:load` tá problemático mesmo?

**Comment by Bouckaert** [comment]
Closed by: https://github.com/OpenRedu/OpenRedu/commit/d9e111dc4d088e458b22e8ac647f27e21791d2c6
