### ISSUE TITLE
Erro ao executar "rake sunspot:solr:run"

### ISSUE THREAD

**Issue by miguelarauj1o** [OpenRedu/OpenRedu#16]
```
rake aborted!
Failed to connect to a master node at localhost:27017
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongo-1.8.6/lib/mongo/mongo_client.rb:463:in `connect'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongo-1.8.6/lib/mongo/mongo_client.rb:645:in `setup'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongo-1.8.6/lib/mongo/mongo_client.rb:126:in `initialize'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongo-1.8.6/lib/mongo/util/uri_parser.rb:157:in `new'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongo-1.8.6/lib/mongo/util/uri_parser.rb:157:in `connection'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongo-1.8.6/lib/mongo/mongo_client.rb:174:in `from_uri'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongoid-2.7.1/lib/mongoid/config/database.rb:86:in `master'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongoid-2.7.1/lib/mongoid/config/database.rb:19:in `configure'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongoid-2.7.1/lib/mongoid/config.rb:290:in `configure_databases'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongoid-2.7.1/lib/mongoid/config.rb:111:in `from_hash'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongoid-2.7.1/lib/mongoid/config.rb:126:in `block in load!'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongoid-2.7.1/lib/mongoid/config.rb:125:in `tap'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongoid-2.7.1/lib/mongoid/config.rb:125:in `load!'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongoid-2.7.1/lib/mongoid.rb:148:in `load!'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/mongoid-2.7.1/lib/mongoid/railtie.rb:84:in `block in <class:Railtie>'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `instance_exec'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `run'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `each'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `run_initializers'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/application.rb:136:in `initialize!'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/miguel/Documents/OpenRedu/config/environment.rb:6:in `<top (required)>'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/application.rb:103:in `require_environment!'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.13/lib/rails/application.rb:297:in `block (2 levels) in initialize_tasks'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:205:in `block in invoke_prerequisites'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:183:in `block in invoke_with_call_chain'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/miguel/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
Tasks: TOP => sunspot:solr:run => environment
(See full trace by running task with --trace)
```

**Comment by Bouckaert** [comment]
@miguelarauj1o Qual o cenário que levou ao erro? No [setup](https://github.com/OpenRedu/OpenRedu/wiki/OpenRedu-Setup-%28Ubuntu%29) atualizado substitui:

> $ rake sunspot:solr:run

por

> $ rake sunspot:solr:start

**Comment by miguelarauj1o** [comment]
Olha, eu tentei novamente a parte do _rake_ há pouco tempo atrás e funcionou. Acho que foi isso...
Eu esqueci de ter avisado logo.
